apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: default
data:
  GITEA__database__DB_TYPE: postgres
  GITEA__database__HOST: localhost:5432
  GITEA__database__NAME: gitea
  GITEA__database__USER: gitea
  GITEA__database__PASSWD: gitea

