apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh-service
spec:
  selector:
    app: gitea
  type: LoadBalancer 
  ports:
    - name: gitea-ssh
      protocol: TCP
      port: 222
      targetPort: gitea-ssh-port
