apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: gitea
  type: ClusterIP 
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: postgres-port 
